name: Check Domain Availability

on:
  schedule:
    # 每天 UTC 时间 0 点运行（北京时间 8 点）
    - cron: '0 0 * * *'
  workflow_dispatch: # 允许手动触发

jobs:
  check-domain:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install python-whois requests

      - name: Run domain check script
        env:
          TELEGRAM_BOT_TOKEN: ${{ secrets.TELEGRAM_BOT_TOKEN }}
          TELEGRAM_CHAT_ID: ${{ secrets.TELEGRAM_CHAT_ID }}
        run: |
          python check_domain.py
